services:
  redis:
    image: redis:7.2
    container_name: bonsai-redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  bonsaid:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bonsaid
    restart: always
    depends_on:
      - redis
    environment:
      SVC_PORT: "8080"
      API_PORT: "8081"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    ports:
      - "8080:8080"
      - "8081:8081"

  bonsai-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder # Use the build stage
    container_name: bonsai-test
    command: /bonsai-test
    depends_on:
      - bonsaid
      - redis
    profiles: [test]

volumes:
  redis_data:
